---
openapi: 3.0.0
info:
  title: RFID Security Service
  description: This API allows the management of RFID media, permissions and associations
  contact:
    email: Brian.Curnow@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /api/v1.0
  description: Version 1.0
paths:
  /media/{media_id}:
    get:
      summary: Retrieves media by id
      description: |
        Takes a media_id and returns the media
      parameters:
      - name: media_id
        in: path
        description: the id of the requested media
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Media object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        "400":
          description: Invalid request
        "401":
          description: You must authenticate to access this path
        "404":
          description: Media not found
components:
  schemas:
    Media:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Anna's MagicBand
        desc:
          type: string
          example: This is the MagicBand that Anna got from Elsa
